# Generated by Django 2.2.24 on 2022-01-13 07:40

from django.db import migrations
import phonenumbers


def is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().only('construction_year', 'new_building'):
        flat.new_building = True if flat.construction_year >= 2015 else False
        flat.save()


def serialize_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().only('owners_phonenumber', 'owner_pure_number'):
        number = flat.owners_phonenumber
        number_to_serialize = phonenumbers.parse(number, 'RU')
        if phonenumbers.is_valid_number(number_to_serialize):
            flat.owner_pure_number = phonenumbers.format_number(number_to_serialize, phonenumbers.PhoneNumberFormat.E164)
            flat.save()


def add_owners_to_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all().only('owner', 'owners_phonenumber', 'owner_pure_number')
    for flat in flats:
        Owner.objects.get_or_create(
            flat_owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_number=flat.owner_pure_number
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(is_new_building),
        migrations.RunPython(serialize_number),
        migrations.RunPython(add_owners_to_model),
    ]
