# Generated by Django 2.2.24 on 2022-01-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20220113_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='flats_in_own', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
