# Generated by Django 2.2.24 on 2022-01-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20220112_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain',
            options={'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
    ]
