# Generated by Django 2.2.24 on 2022-01-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20220114_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_number',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
